import type { Question } from './types';

const P4: Question[] = [
  {
    id: 'b4-01',
    topic: 'spatial',
    points: 4,
    visual: '🧊',
    text: 'Một hình được xếp bằng các khối lập phương: tầng dưới có 4 khối, tầng trên có 2 khối. Có tất cả bao nhiêu khối lập phương?',
    options: [
      { key: 'A', text: '4 khối' },
      { key: 'B', text: '5 khối' },
      { key: 'C', text: '6 khối' },
      { key: 'D', text: '7 khối' },
      { key: 'E', text: '8 khối' },
    ],
    correct: 'C',
    explanation: ['Tầng dưới 4 khối + tầng trên 2 khối = 6 khối.'],
    takeaway: 'Đếm khối theo từng tầng rồi cộng lại.',
  },
  {
    id: 'b4-02',
    topic: 'arithmetic',
    points: 4,
    visual: '🍓',
    text: 'Mỗi cái giỏ có 5 quả dâu. Có 3 cái giỏ như vậy. Tổng cộng có bao nhiêu quả dâu?',
    options: [
      { key: 'A', text: '8 quả' },
      { key: 'B', text: '12 quả' },
      { key: 'C', text: '15 quả' },
      { key: 'D', text: '18 quả' },
      { key: 'E', text: '10 quả' },
    ],
    correct: 'C',
    explanation: ['5 + 5 + 5 = 15, hay 5 × 3 = 15 (quả).'],
    takeaway: 'Cộng nhiều nhóm bằng nhau = phép nhân.',
  },
  {
    id: 'b4-03',
    topic: 'logic',
    points: 4,
    visual: '🐰🐱🐶',
    text: 'Thỏ nặng hơn Mèo, Mèo nặng hơn Chó. Con nào nhẹ nhất?',
    options: [
      { key: 'A', text: 'Thỏ' },
      { key: 'B', text: 'Mèo' },
      { key: 'C', text: 'Chó' },
      { key: 'D', text: 'Bằng nhau' },
      { key: 'E', text: 'Không rõ' },
    ],
    correct: 'C',
    explanation: ['Thỏ > Mèo > Chó.', 'Chó đứng cuối nên nhẹ nhất.'],
    takeaway: 'Xếp thứ tự từ nặng đến nhẹ để tìm con nhẹ nhất.',
  },
  {
    id: 'b4-04',
    topic: 'measurement',
    points: 4,
    visual: '🕐',
    text: 'Bây giờ là 7 giờ 30 phút. Hỏi 1 giờ nữa (60 phút sau) là mấy giờ?',
    options: [
      { key: 'A', text: '8 giờ' },
      { key: 'B', text: '8 giờ 30 phút' },
      { key: 'C', text: '9 giờ' },
      { key: 'D', text: '7 giờ 30 phút' },
      { key: 'E', text: '6 giờ 30 phút' },
    ],
    correct: 'B',
    explanation: ['7 giờ 30 + 1 giờ = 8 giờ 30 phút.'],
    takeaway: 'Cộng thêm giờ, phần phút giữ nguyên.',
  },
  {
    id: 'b4-05',
    topic: 'arithmetic',
    points: 4,
    visual: '🔺🔺',
    text: 'Quy luật: 1, 3, 5, 7, ... Số thứ sáu trong dãy là số nào?',
    options: [
      { key: 'A', text: '9' },
      { key: 'B', text: '10' },
      { key: 'C', text: '11' },
      { key: 'D', text: '13' },
      { key: 'E', text: '12' },
    ],
    correct: 'C',
    explanation: ['Dãy số lẻ: 1, 3, 5, 7, 9, 11.', 'Số thứ sáu là 11.'],
    takeaway: 'Viết tiếp dãy đến đúng vị trí cần tìm.',
  },
  {
    id: 'b4-06',
    topic: 'spatial',
    points: 4,
    visual: '🪞',
    text: 'Chữ cái nào KHÔNG thay đổi khi soi qua gương (đối xứng trái–phải)?',
    options: [
      { key: 'A', text: 'A' },
      { key: 'B', text: 'F' },
      { key: 'C', text: 'G' },
      { key: 'D', text: 'R' },
      { key: 'E', text: 'P' },
    ],
    correct: 'A',
    explanation: ['Chữ A có trục đối xứng đứng nên soi gương vẫn giống nhau.', 'F, G, R, P thì bị đổi ngược.'],
    takeaway: 'Chữ có trục đối xứng dọc thì không đổi khi soi gương.',
  },
  {
    id: 'b4-07',
    topic: 'logic',
    points: 4,
    visual: '🚌',
    text: 'Trên xe buýt có 12 bạn. Đến bến, 5 bạn xuống và 3 bạn lên. Bây giờ trên xe có bao nhiêu bạn?',
    options: [
      { key: 'A', text: '8 bạn' },
      { key: 'B', text: '9 bạn' },
      { key: 'C', text: '10 bạn' },
      { key: 'D', text: '11 bạn' },
      { key: 'E', text: '14 bạn' },
    ],
    correct: 'C',
    explanation: ['Sau khi xuống: 12 − 5 = 7.', 'Sau khi lên: 7 + 3 = 10 (bạn).'],
    takeaway: 'Xử lý lần lượt: xuống trước, lên sau.',
  },
  {
    id: 'b4-08',
    topic: 'measurement',
    points: 4,
    visual: '📏',
    text: 'Con ếch nhảy mỗi bước dài 2 ô. Nó xuất phát ở ô số 0. Sau 4 bước nhảy, ếch ở ô số mấy?',
    options: [
      { key: 'A', text: '6' },
      { key: 'B', text: '7' },
      { key: 'C', text: '8' },
      { key: 'D', text: '10' },
      { key: 'E', text: '4' },
    ],
    correct: 'C',
    explanation: ['Mỗi bước +2, sau 4 bước: 2 × 4 = 8.', 'Ếch ở ô số 8.'],
    takeaway: 'Số ô = độ dài bước × số bước.',
  },
  {
    id: 'b4-09',
    topic: 'arithmetic',
    points: 4,
    visual: '🍎🍌',
    text: 'Biết 🍎 = 5 và 🍎 + 🍌 = 9. Vậy 🍌 bằng bao nhiêu?',
    options: [
      { key: 'A', text: '3' },
      { key: 'B', text: '4' },
      { key: 'C', text: '5' },
      { key: 'D', text: '9' },
      { key: 'E', text: '14' },
    ],
    correct: 'B',
    explanation: ['🍌 = 9 − 🍎 = 9 − 5 = 4.'],
    takeaway: 'Biểu tượng thay số: thay giá trị đã biết vào rồi tính.',
  },
  {
    id: 'b4-10',
    topic: 'spatial',
    points: 4,
    visual: '🧩',
    text: 'Một hình vuông được cắt thành 4 mảnh bằng nhau. Đã ghép được 3 mảnh. Còn thiếu mấy phần để hoàn thành?',
    options: [
      { key: 'A', text: '1 mảnh' },
      { key: 'B', text: '2 mảnh' },
      { key: 'C', text: '3 mảnh' },
      { key: 'D', text: '4 mảnh' },
      { key: 'E', text: '0 mảnh' },
    ],
    correct: 'A',
    explanation: ['Tổng 4 mảnh, đã có 3 mảnh.', 'Còn thiếu: 4 − 3 = 1 (mảnh).'],
    takeaway: 'Lấy tổng số mảnh trừ số mảnh đã ghép.',
  },
];

export default P4;
