import type { Question } from './types';

// ============================================================
// NGÂN HÀNG CÂU HỎI IKMC Level 1 (Lớp 2)
// 4 nhóm: arithmetic, spatial, measurement, logic
// 3 mức điểm: 3đ (Phần A), 4đ (Phần B), 5đ (Phần C)
// Tối thiểu > 8 câu mỗi mức để bốc đề ngẫu nhiên.
// ============================================================

const P3: Question[] = [
  {
    id: 'a3-01',
    topic: 'arithmetic',
    points: 3,
    visual: '🥕',
    text: 'Chú thỏ có 3 củ cà rốt. Chú ăn 1 củ vào buổi sáng, rồi mẹ cho thêm 4 củ. Bây giờ chú thỏ có bao nhiêu củ cà rốt?',
    options: [
      { key: 'A', text: '5 củ' },
      { key: 'B', text: '6 củ' },
      { key: 'C', text: '7 củ' },
      { key: 'D', text: '8 củ' },
      { key: 'E', text: '4 củ' },
    ],
    correct: 'B',
    explanation: [
      'Sau khi ăn: 3 − 1 = 2 (củ).',
      'Được cho thêm: 2 + 4 = 6 (củ).',
    ],
    takeaway: 'Làm lần lượt từng bước: bớt trước, thêm sau.',
  },
  {
    id: 'a3-02',
    topic: 'arithmetic',
    points: 3,
    visual: '🍎🍎🍎',
    text: 'Dãy số cách đều: 2, 4, 6, 8, ... Số tiếp theo là số nào?',
    options: [
      { key: 'A', text: '9' },
      { key: 'B', text: '10' },
      { key: 'C', text: '11' },
      { key: 'D', text: '12' },
      { key: 'E', text: '7' },
    ],
    correct: 'B',
    explanation: ['Mỗi số hơn số trước 2 đơn vị.', '8 + 2 = 10.'],
    takeaway: 'Tìm khoảng cách giữa hai số liền nhau rồi cộng tiếp.',
  },
  {
    id: 'a3-03',
    topic: 'logic',
    points: 3,
    visual: '🔺🟦🔺🟦',
    text: 'Quy luật hình lặp lại: 🔺 🟦 🔺 🟦 🔺 ... Hình tiếp theo là gì?',
    options: [
      { key: 'A', text: '🔺 (tam giác)' },
      { key: 'B', text: '🟦 (hình vuông)' },
      { key: 'C', text: '⭐ (ngôi sao)' },
      { key: 'D', text: '⚫ (hình tròn)' },
      { key: 'E', text: 'Không có hình' },
    ],
    correct: 'B',
    explanation: ['Chu kỳ lặp là 🔺 🟦.', 'Sau 🔺 luôn là 🟦.'],
    takeaway: 'Tìm cụm lặp (chu kỳ) rồi suy ra hình kế tiếp.',
  },
  {
    id: 'a3-04',
    topic: 'measurement',
    points: 3,
    visual: '⏰',
    text: 'Đồng hồ chỉ 3 giờ đúng. Sau 2 giờ nữa thì đồng hồ chỉ mấy giờ?',
    options: [
      { key: 'A', text: '4 giờ' },
      { key: 'B', text: '5 giờ' },
      { key: 'C', text: '6 giờ' },
      { key: 'D', text: '2 giờ' },
      { key: 'E', text: '1 giờ' },
    ],
    correct: 'B',
    explanation: ['3 giờ + 2 giờ = 5 giờ.'],
    takeaway: 'Cộng thêm số giờ vào giờ hiện tại.',
  },
  {
    id: 'a3-05',
    topic: 'arithmetic',
    points: 3,
    visual: '🍬',
    text: 'An có 10 viên kẹo, cho em 3 viên và cho bạn 2 viên. An còn lại bao nhiêu viên kẹo?',
    options: [
      { key: 'A', text: '4 viên' },
      { key: 'B', text: '5 viên' },
      { key: 'C', text: '6 viên' },
      { key: 'D', text: '7 viên' },
      { key: 'E', text: '3 viên' },
    ],
    correct: 'B',
    explanation: ['Cho đi tất cả: 3 + 2 = 5 (viên).', 'Còn lại: 10 − 5 = 5 (viên).'],
    takeaway: 'Gộp số cho đi trước, rồi trừ khỏi tổng ban đầu.',
  },
  {
    id: 'a3-06',
    topic: 'spatial',
    points: 3,
    visual: '🟥🟥🟥',
    text: 'Minh xếp hình chữ L bằng khối gỗ: 3 khối dựng đứng và 2 khối nằm ngang. Minh dùng tất cả bao nhiêu khối?',
    options: [
      { key: 'A', text: '4 khối' },
      { key: 'B', text: '5 khối' },
      { key: 'C', text: '6 khối' },
      { key: 'D', text: '7 khối' },
      { key: 'E', text: '8 khối' },
    ],
    correct: 'B',
    explanation: ['3 khối dọc + 2 khối ngang = 5 khối.'],
    takeaway: 'Đếm từng phần rồi cộng lại.',
  },
  {
    id: 'a3-07',
    topic: 'logic',
    points: 3,
    visual: '🐤🐤🐤🐤🐤',
    text: 'Có 5 chú gà con xếp thành hàng. Bạn Cún đứng thứ 2 từ trái sang. Bên phải Cún còn mấy chú gà?',
    options: [
      { key: 'A', text: '2 chú' },
      { key: 'B', text: '3 chú' },
      { key: 'C', text: '4 chú' },
      { key: 'D', text: '1 chú' },
      { key: 'E', text: '5 chú' },
    ],
    correct: 'B',
    explanation: ['Cún là con thứ 2, còn lại phía sau: 5 − 2 = 3 (chú).'],
    takeaway: 'Lấy tổng trừ đi vị trí đang đứng.',
  },
  {
    id: 'a3-08',
    topic: 'measurement',
    points: 3,
    visual: '⚖️',
    text: 'Cân thăng bằng: 1 quả táo nặng bằng 2 quả mận. Vậy 2 quả táo nặng bằng mấy quả mận?',
    options: [
      { key: 'A', text: '2 quả mận' },
      { key: 'B', text: '3 quả mận' },
      { key: 'C', text: '4 quả mận' },
      { key: 'D', text: '5 quả mận' },
      { key: 'E', text: '6 quả mận' },
    ],
    correct: 'C',
    explanation: ['1 táo = 2 mận.', '2 táo = 2 × 2 = 4 mận.'],
    takeaway: 'Nhân đôi vật thì cũng nhân đôi số vật cân bằng.',
  },
  {
    id: 'a3-09',
    topic: 'arithmetic',
    points: 3,
    visual: '🌸🌸',
    text: 'Trong vườn có 6 bông hoa đỏ và 7 bông hoa vàng. Có tất cả bao nhiêu bông hoa?',
    options: [
      { key: 'A', text: '12 bông' },
      { key: 'B', text: '13 bông' },
      { key: 'C', text: '14 bông' },
      { key: 'D', text: '11 bông' },
      { key: 'E', text: '15 bông' },
    ],
    correct: 'B',
    explanation: ['6 + 7 = 13 (bông).'],
    takeaway: 'Cộng hai nhóm để tìm tổng.',
  },
  {
    id: 'a3-10',
    topic: 'logic',
    points: 3,
    visual: '🍦',
    text: 'Bốn bạn xếp hàng mua kem: Lan, Mai, Nam, Hoa (theo thứ tự trước sau). Ai là người đứng cuối cùng?',
    options: [
      { key: 'A', text: 'Lan' },
      { key: 'B', text: 'Mai' },
      { key: 'C', text: 'Nam' },
      { key: 'D', text: 'Hoa' },
      { key: 'E', text: 'Không rõ' },
    ],
    correct: 'D',
    explanation: ['Thứ tự: Lan → Mai → Nam → Hoa.', 'Người cuối cùng là Hoa.'],
    takeaway: 'Người được nhắc sau cùng là người đứng cuối.',
  },
];

export default P3;
