import type { Question } from './types';

const P5: Question[] = [
  {
    id: 'c5-01',
    topic: 'logic',
    points: 5,
    visual: '🧍‍♂️',
    text: 'Một hàng có 7 bạn. Bạn Nam đứng thứ 3 tính từ đầu hàng. Hỏi Nam đứng thứ mấy nếu đếm từ cuối hàng lên?',
    options: [
      { key: 'A', text: 'Thứ 3' },
      { key: 'B', text: 'Thứ 4' },
      { key: 'C', text: 'Thứ 5' },
      { key: 'D', text: 'Thứ 6' },
      { key: 'E', text: 'Thứ 2' },
    ],
    correct: 'C',
    explanation: ['Sau Nam có: 7 − 3 = 4 (bạn).', 'Đếm từ cuối lên: 4 + 1 = thứ 5.'],
    takeaway: 'Vị trí từ cuối = (tổng − vị trí từ đầu) + 1.',
  },
  {
    id: 'c5-02',
    topic: 'spatial',
    points: 5,
    visual: '🧊',
    text: 'Một khối lớn xếp bằng lập phương nhỏ: 3 tầng, mỗi tầng 4 khối. Có tất cả bao nhiêu khối lập phương nhỏ?',
    options: [
      { key: 'A', text: '7 khối' },
      { key: 'B', text: '10 khối' },
      { key: 'C', text: '12 khối' },
      { key: 'D', text: '9 khối' },
      { key: 'E', text: '8 khối' },
    ],
    correct: 'C',
    explanation: ['Mỗi tầng 4 khối, 3 tầng: 4 × 3 = 12 (khối).'],
    takeaway: 'Số khối = số khối mỗi tầng × số tầng.',
  },
  {
    id: 'c5-03',
    topic: 'measurement',
    points: 5,
    visual: '⚖️',
    text: 'Cân thăng bằng: 3 quả cam nặng bằng 6 quả nho. Vậy 1 quả cam nặng bằng mấy quả nho?',
    options: [
      { key: 'A', text: '1 quả nho' },
      { key: 'B', text: '2 quả nho' },
      { key: 'C', text: '3 quả nho' },
      { key: 'D', text: '6 quả nho' },
      { key: 'E', text: '4 quả nho' },
    ],
    correct: 'B',
    explanation: ['3 cam = 6 nho, chia đều cho 3.', '1 cam = 6 ÷ 3 = 2 nho.'],
    takeaway: 'Chia đều hai đĩa cân cho cùng một số.',
  },
  {
    id: 'c5-04',
    topic: 'logic',
    points: 5,
    visual: '🔢',
    text: 'Điền số vào ô trống để mỗi hàng ngang có tổng bằng 10: hàng có 4 và 3 rồi ô trống. Ô trống là số mấy?',
    options: [
      { key: 'A', text: '2' },
      { key: 'B', text: '3' },
      { key: 'C', text: '4' },
      { key: 'D', text: '5' },
      { key: 'E', text: '7' },
    ],
    correct: 'B',
    explanation: ['4 + 3 = 7.', 'Cần thêm: 10 − 7 = 3.'],
    takeaway: 'Lấy tổng mong muốn trừ đi các số đã có.',
  },
  {
    id: 'c5-05',
    topic: 'arithmetic',
    points: 5,
    visual: '🍭',
    text: 'Có 20 cái kẹo chia đều cho 4 bạn. Sau đó mỗi bạn ăn 2 cái. Bây giờ mỗi bạn còn mấy cái kẹo?',
    options: [
      { key: 'A', text: '2 cái' },
      { key: 'B', text: '3 cái' },
      { key: 'C', text: '4 cái' },
      { key: 'D', text: '5 cái' },
      { key: 'E', text: '6 cái' },
    ],
    correct: 'B',
    explanation: ['Chia đều: 20 ÷ 4 = 5 (cái mỗi bạn).', 'Sau khi ăn: 5 − 2 = 3 (cái).'],
    takeaway: 'Chia đều trước, rồi trừ phần đã dùng.',
  },
  {
    id: 'c5-06',
    topic: 'logic',
    points: 5,
    visual: '🐿️',
    text: 'Sóc đi qua mê cung nhặt hạt dẻ, mỗi ô chỉ được đi 1 lần. Có 3 đường: đường 1 nhặt 4 hạt, đường 2 nhặt 6 hạt, đường 3 nhặt 5 hạt. Sóc nhặt được nhiều nhất bao nhiêu hạt?',
    options: [
      { key: 'A', text: '4 hạt' },
      { key: 'B', text: '5 hạt' },
      { key: 'C', text: '6 hạt' },
      { key: 'D', text: '15 hạt' },
      { key: 'E', text: '7 hạt' },
    ],
    correct: 'C',
    explanation: ['So sánh 3 đường: 4, 6, 5.', 'Đường nhiều nhất là 6 hạt.'],
    takeaway: 'So sánh các lựa chọn để tìm giá trị lớn nhất.',
  },
  {
    id: 'c5-07',
    topic: 'measurement',
    points: 5,
    visual: '📅',
    text: 'Hôm nay là thứ Hai. Hỏi sau 3 ngày nữa là thứ mấy?',
    options: [
      { key: 'A', text: 'Thứ Ba' },
      { key: 'B', text: 'Thứ Tư' },
      { key: 'C', text: 'Thứ Năm' },
      { key: 'D', text: 'Thứ Sáu' },
      { key: 'E', text: 'Chủ Nhật' },
    ],
    correct: 'C',
    explanation: ['Thứ Hai → +1 Thứ Ba → +2 Thứ Tư → +3 Thứ Năm.'],
    takeaway: 'Đếm tiến từng ngày trong tuần.',
  },
  {
    id: 'c5-08',
    topic: 'arithmetic',
    points: 5,
    visual: '🎈',
    text: 'Biểu tượng thay số: ⭐ + ⭐ = 8 và ⭐ + 🌙 = 7. Hỏi 🌙 bằng bao nhiêu?',
    options: [
      { key: 'A', text: '2' },
      { key: 'B', text: '3' },
      { key: 'C', text: '4' },
      { key: 'D', text: '5' },
      { key: 'E', text: '7' },
    ],
    correct: 'B',
    explanation: ['⭐ + ⭐ = 8 nên ⭐ = 4.', '🌙 = 7 − ⭐ = 7 − 4 = 3.'],
    takeaway: 'Tìm giá trị dễ trước (⭐), rồi suy ra giá trị còn lại.',
  },
  {
    id: 'c5-09',
    topic: 'spatial',
    points: 5,
    visual: '🗺️',
    text: 'Tô màu bản đồ 4 ô xếp thành hàng ngang, hai ô cạnh nhau không được cùng màu. Cần ít nhất mấy màu?',
    options: [
      { key: 'A', text: '1 màu' },
      { key: 'B', text: '2 màu' },
      { key: 'C', text: '3 màu' },
      { key: 'D', text: '4 màu' },
      { key: 'E', text: '5 màu' },
    ],
    correct: 'B',
    explanation: ['Tô xen kẽ: màu 1 – màu 2 – màu 1 – màu 2.', 'Chỉ cần 2 màu là đủ.'],
    takeaway: 'Với dãy thẳng, tô xen kẽ 2 màu là đủ.',
  },
  {
    id: 'c5-10',
    topic: 'logic',
    points: 5,
    visual: '👧👦',
    text: 'Lan nhiều tuổi hơn Bình 2 tuổi. Bình 6 tuổi. Tổng số tuổi của hai bạn là bao nhiêu?',
    options: [
      { key: 'A', text: '12 tuổi' },
      { key: 'B', text: '13 tuổi' },
      { key: 'C', text: '14 tuổi' },
      { key: 'D', text: '10 tuổi' },
      { key: 'E', text: '8 tuổi' },
    ],
    correct: 'C',
    explanation: ['Lan: 6 + 2 = 8 (tuổi).', 'Tổng: 8 + 6 = 14 (tuổi).'],
    takeaway: 'Tìm tuổi từng người trước, rồi cộng lại.',
  },
];

export default P5;
